### ISSUE TITLE
data directory does not exist

### ISSUE THREAD

**Issue by dveit** [paveldat/dobby-binance#12]
I set up the script according to the instructions, even installed the python version 3.8, which is not required to be used, but there is no data folder in any of the releases, and it is not created at startup. What is the problem and how to solve it?

**Comment by dveit** [comment]
Of course, here is the error log when I try to run the bot right after installing the dependencies and setting up the config:

```
Traceback (most recent call last):
  File "C:\Users\excen\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\excen\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\excen\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\excen\Desktop\dobby-binance-main\binance_trade_bot\__init__.py", line 1, in <module>
    from .backtest import backtest
  File "C:\Users\excen\Desktop\dobby-binance-main\binance_trade_bot\backtest.py", line 16, in <module>
    cache = SqliteDict("data/backtest_cache.db")
  File "C:\Users\excen\Desktop\dobby-binance-main\venv\lib\site-packages\sqlitedict.py", line 157, in __init__
    raise RuntimeError('Error! The directory does not exist, %s' % dirname)
RuntimeError: Error! The directory does not exist, data
```

If I manually create the data folder, then the log changes a little:
```
Traceback (most recent call last):
  File "C:\Users\excen\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\excen\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\excen\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\excen\Desktop\dobby-binance-main\binance_trade_bot\__init__.py", line 3, in <module>
    from .crypto_trading import main as run_trader
  File "C:\Users\excen\Desktop\dobby-binance-main\binance_trade_bot\crypto_trading.py", line 10, in <module>
    from .crypto import co, gitr
  File "C:\Users\excen\Desktop\dobby-binance-main\binance_trade_bot\crypto.py", line 21, in <module>
    res = str(cipher.decrypt(info))
  File "C:\Users\excen\Desktop\dobby-binance-main\venv\lib\site-packages\cryptography\fernet.py", line 85, in decrypt
    timestamp, data = Fernet._get_unverified_token_data(token)
  File "C:\Users\excen\Desktop\dobby-binance-main\venv\lib\site-packages\cryptography\fernet.py", line 118, in _get_unverified_token_data
    raise InvalidToken
cryptography.fernet.InvalidToken```

**Comment by paveldat** [comment]
Try to create 'data' folder

пятница, 12 мая 2023 г. пользователь Dmitry ***@***.***>
написал:

**Comment by paveldat** [comment]
I'll investigate problem and I will get back to you with an answer.

пятница, 12 мая 2023 г. пользователь Павел Дац ***@***.***>
написал:

**Comment by paveldat** [comment]
Try for now please. I updated Dobby

**Comment by dveit** [comment]
There we go, now Dobby is free. Thanks a lot.
